// Curated word lists for Wordle - common English words
// 5-letter: ~300 words, 6-letter: ~250 words, 7-letter: ~200 words

export const WORDS_5 = [
  "about", "above", "actor", "adult", "after", "again", "agent", "agree", "ahead", "alarm",
  "album", "alert", "alike", "alive", "allow", "alone", "along", "alter", "among", "angel",
  "anger", "angle", "angry", "apart", "apple", "arena", "argue", "arise", "array", "aside",
  "asset", "avoid", "award", "aware", "badly", "baker", "bases", "basic", "basis", "beach",
  "began", "begin", "begun", "being", "below", "bench", "billy", "birth", "black", "blade",
  "blame", "blank", "blast", "bleed", "bless", "blind", "block", "blood", "board", "boost",
  "booth", "bound", "brain", "brand", "brass", "brave", "bread", "break", "breed", "brick",
  "brief", "bring", "broad", "broke", "build", "built", "burst", "buyer", "cabin", "cable",
  "calif", "carry", "catch", "cause", "chain", "chair", "chart", "chase", "cheap", "check",
  "chest", "chief", "child", "china", "chose", "civil", "claim", "class", "clean", "clear",
  "click", "climb", "clock", "close", "cloth", "cloud", "coach", "coast", "color", "comic",
  "couch", "could", "count", "court", "cover", "crack", "craft", "crash", "crazy", "cream",
  "crime", "cross", "crowd", "crown", "curve", "cycle", "daily", "dance", "dated", "dealt",
  "death", "debut", "delay", "delta", "dense", "depth", "dirty", "doubt", "dozen", "draft",
  "drama", "drawn", "dream", "dress", "drill", "drink", "drive", "drove", "dying", "eager",
  "early", "earth", "eight", "elder", "elect", "empty", "enemy", "enjoy", "enter", "entry",
  "equal", "error", "event", "every", "exact", "exist", "extra", "faith", "false", "fault",
  "fiber", "field", "fifth", "fifty", "fight", "final", "first", "fixed", "flash", "fleet",
  "floor", "fluid", "focus", "force", "forth", "forty", "forum", "found", "frame", "frank",
  "fresh", "front", "fruit", "fully", "funny", "giant", "given", "glass", "globe", "glory",
  "going", "grace", "grade", "grain", "grand", "grant", "grass", "great", "green", "gross",
  "group", "grown", "guard", "guess", "guest", "guide", "happy", "harry", "heart", "heavy",
  "hello", "hence", "horse", "hotel", "house", "human", "ideal", "image", "index", "inner",
  "input", "issue", "japan", "joint", "jones", "judge", "juice", "known", "label", "large",
  "laser", "later", "laugh", "layer", "learn", "least", "leave", "legal", "level", "light",
  "limit", "local", "logic", "loose", "lunch", "lying", "magic", "major", "maker", "march",
  "match", "maybe", "mayor", "meant", "media", "metal", "meter", "midst", "might", "minor",
  "minus", "mixed", "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth",
  "movie", "music", "naked", "nasty", "naval", "needs", "never", "newly", "night", "noise",
  "north", "noted", "novel", "nurse", "occur", "ocean", "offer", "often", "order", "other",
  "ought", "paint", "panel", "paper", "party", "peace", "phase", "phone", "photo", "piece",
  "pilot", "pitch", "place", "plain", "plane", "plant", "plate", "point", "pound", "power",
  "press", "price", "pride", "prime", "print", "prior", "prize", "proof", "proud", "prove",
  "queen", "quick", "quiet", "quite", "quote", "radio", "raise", "range", "rapid", "ratio",
  "reach", "ready", "refer", "right", "rival", "river", "roman", "rough", "round", "route",
  "royal", "rural", "scale", "scene", "scope", "score", "sense", "serve", "seven", "shall",
  "shape", "share", "sharp", "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock",
  "shoot", "short", "shown", "sight", "since", "skill", "sleep", "slide", "small", "smart",
  "smile", "smith", "smoke", "solid", "solve", "sorry", "sound", "south", "space", "spare",
  "speak", "speed", "spend", "spent", "split", "spoke", "sport", "staff", "stage", "stake",
  "stand", "start", "state", "steam", "steel", "stick", "still", "stock", "stone", "stood",
  "store", "storm", "story", "strip", "stuck", "study", "stuff", "style", "sugar", "suite",
  "super", "sweet", "table", "taken", "taste", "teach", "teeth", "thank", "theme", "thing",
  "think", "third", "those", "three", "throw", "tight", "times", "title", "today", "total",
  "touch", "tough", "tower", "track", "trade", "train", "treat", "trend", "trial", "tribe",
  "trick", "tried", "truck", "truly", "trust", "truth", "twice", "under", "union", "unity",
  "until", "upper", "urban", "usual", "valid", "value", "video", "virus", "visit", "vital",
  "voice", "waste", "watch", "water", "wheel", "where", "which", "while", "white", "whole",
  "whose", "woman", "women", "world", "worry", "worse", "worst", "worth", "would", "wound",
  "write", "wrong", "wrote", "yield", "young", "youth",
];

export const WORDS_6 = [
  "action", "active", "actual", "advice", "affect", "afford", "afraid", "agency", "agenda", "almost",
  "always", "amount", "animal", "annual", "answer", "anyone", "anyway", "appeal", "appear", "around",
  "artist", "assess", "assist", "assume", "attack", "attempt", "attend", "author", "avenue", "backed",
  "barely", "battle", "beauty", "became", "before", "behalf", "behind", "belief", "belong", "better",
  "beyond", "bishop", "border", "bottle", "branch", "breast", "bridge", "bright", "broken", "budget",
  "burden", "bureau", "button", "camera", "cancer", "cannot", "carbon", "career", "castle", "casual",
  "caught", "center", "chance", "change", "charge", "choice", "choose", "church", "circle", "client",
  "closed", "closer", "coffee", "column", "combat", "coming", "common", "comply", "copper", "corner",
  "cotton", "county", "couple", "course", "covers", "create", "credit", "crisis", "custom", "damage",
  "danger", "dealer", "debate", "decade", "decide", "defeat", "defend", "define", "degree", "demand",
  "depend", "deputy", "desert", "design", "desire", "detail", "device", "differ", "dinner", "direct",
  "doctor", "dollar", "domain", "double", "driven", "driver", "during", "easily", "eating", "editor",
  "effect", "effort", "eighth", "either", "eleven", "emerge", "empire", "employ", "enable", "energy",
  "engage", "engine", "ensure", "entire", "entity", "equity", "escape", "estate", "ethnic", "europe",
  "events", "except", "excess", "expand", "expect", "expert", "export", "extend", "extent", "fabric",
  "facing", "factor", "failed", "fairly", "fallen", "family", "famous", "father", "fellow", "female",
  "figure", "finger", "finish", "fiscal", "flight", "flying", "follow", "forest", "forget", "formal",
  "format", "former", "foster", "fought", "fourth", "french", "friend", "future", "garden", "gather",
  "gender", "german", "global", "golden", "govern", "ground", "growth", "guilty", "handed", "handle",
  "happen", "hardly", "health", "height", "helped", "hidden", "holder", "honest", "impact", "import",
  "income", "indeed", "injury", "inside", "intend", "island", "itself", "jacket", "junior", "killed",
  "labour", "latest", "latter", "leader", "league", "length", "likely", "linked", "listen", "little",
  "living", "losing", "luxury", "mainly", "making", "manage", "manner", "margin", "marine", "master",
  "matter", "medium", "member", "memory", "mental", "method", "middle", "minute", "mobile", "modern",
  "modest", "module", "moment", "mostly", "mother", "motion", "moving", "murder", "museum", "mutual",
  "narrow", "nation", "native", "nature", "nobody", "normal", "notice", "number", "object", "obtain",
  "office", "option", "orange", "origin", "output", "oxford", "parent", "partly", "people", "period",
  "permit", "person", "phrase", "planet", "player", "please", "plenty", "pocket", "policy", "proper",
  "public", "purple", "raised", "random", "rarely", "rather", "reader", "really", "reason", "recall",
  "recent", "record", "reduce", "reform", "regard", "region", "relate", "remain", "remote", "remove",
  "repair", "repeat", "report", "resist", "result", "retire", "return", "review", "reward", "riding",
  "rising", "robust", "ruling", "safety", "sample", "scheme", "school", "screen", "search", "season",
  "second", "secret", "sector", "select", "senior", "series", "server", "settle", "severe", "sexual",
  "should", "signal", "silver", "simple", "single", "sister", "smooth", "social", "source", "speech",
  "spirit", "spoken", "spread", "spring", "square", "stable", "status", "steady", "stream", "street",
  "stress", "strict", "stroke", "strong", "studio", "submit", "summer", "supply", "survey", "switch",
  "symbol", "system", "target", "tender", "thanks", "theory", "thirty", "though", "threat", "thrown",
  "ticket", "timing", "toward", "travel", "treaty", "trying", "twelve", "twenty", "unable", "unique",
  "unless", "update", "useful", "valley", "varied", "virtue", "vision", "visual", "weight", "window",
  "winter", "within", "wonder", "worker", "worthy", "writer", "yellow",
];

export const WORDS_7 = [
  "ability", "account", "achieve", "acquire", "address", "advance", "against", "already", "another", "anxiety",
  "anybody", "attempt", "average", "balance", "barrier", "because", "believe", "benefit", "between", "billion",
  "brother", "browser", "budget", "cabinet", "capital", "captain", "careful", "carrier", "central", "century",
  "certain", "chamber", "channel", "chapter", "citizen", "climate", "closely", "closure", "coastal", "collect",
  "college", "combine", "comfort", "command", "comment", "company", "compare", "compete", "complex", "concept",
  "concern", "conduct", "confirm", "connect", "consist", "contact", "contain", "content", "contest", "context",
  "control", "convert", "council", "country", "courier", "coverage", "created", "culture", "current", "dealing",
  "decided", "default", "defence", "defined", "degree", "deliver", "density", "deposit", "desktop", "despite",
  "destroy", "develop", "differ", "digital", "discuss", "disease", "display", "dispute", "distant", "diverse",
  "divided", "drawing", "driving", "dynamic", "eastern", "economy", "edition", "element", "engaged", "enhance",
  "episode", "evening", "exactly", "example", "excited", "execute", "exercise", "expense", "explain", "explore",
  "express", "extreme", "factory", "failure", "fashion", "feature", "federal", "feeling", "fiction", "fifteen",
  "fighter", "finally", "finance", "finding", "fishing", "fitness", "foreign", "forever", "formula", "forward",
  "founder", "freedom", "further", "gallery", "gateway", "general", "genetic", "growing", "happily", "heading",
  "healthy", "heavily", "helpful", "herself", "himself", "history", "holding", "holiday", "housing", "however",
  "hundred", "husband", "illegal", "illness", "imagine", "improve", "include", "initial", "inquiry", "insight",
  "install", "instant", "instead", "intense", "involve", "journal", "journey", "justice", "kitchen", "knowing",
  "landing", "largely", "leading", "learned", "leather", "leaving", "liberal", "license", "limited", "machine",
  "manager", "married", "massive", "maximum", "meaning", "measure", "medical", "meeting", "mention", "message",
  "million", "minimum", "missing", "mission", "mistake", "mixture", "monitor", "monthly", "morning", "musical",
  "natural", "neither", "network", "nothing", "nowhere", "nuclear", "obvious", "offence", "officer", "opening",
  "operate", "opinion", "organic", "outcome", "outline", "outside", "overall", "package", "painting", "parking",
  "partner", "passage", "passing", "patient", "pattern", "payment", "penalty", "perfect", "perform", "perhaps",
  "physics", "picture", "plastic", "playing", "pleased", "politics", "portion", "poverty", "predict", "present",
  "prevent", "primary", "privacy", "private", "problem", "process", "produce", "product", "profile", "program",
  "project", "promise", "promote", "protect", "provide", "publish", "purpose", "pushing", "qualify", "quality",
  "quarter", "quickly", "reading", "reality", "receive", "recover", "reflect", "regular", "related", "release",
  "remains", "removal", "removed", "replace", "request", "require", "reserve", "resolve", "respect", "respond",
  "restore", "retired", "revenue", "reverse", "rolling", "routine", "running", "satisfy", "science", "section",
  "serious", "service", "session", "setting", "several", "shelter", "shortly", "society", "someone", "sourcing",
  "speaker", "special", "species", "spirit", "station", "storage", "strange", "stretch", "student", "subject",
  "success", "suggest", "support", "suppose", "supreme", "surface", "surgery", "survive", "suspect", "sustain",
  "talking", "teacher", "testing", "therapy", "thought", "through", "tonight", "totally", "tourism", "towards",
  "traffic", "training", "transfer", "trouble", "typical", "uniform", "unknown", "unusual", "upgrade", "usually",
  "various", "vehicle", "version", "village", "violent", "virtual", "visible", "waiting", "walking", "warning",
  "weather", "website", "wedding", "weekend", "welcome", "western", "whether", "willing", "without", "working",
  "writing", "written",
];

export function getRandomWord(length) {
  const lists = { 5: WORDS_5, 6: WORDS_6, 7: WORDS_7 };
  const list = lists[length];
  if (!list) return null;
  return list[Math.floor(Math.random() * list.length)];
}
